config/routes.rb
Demo::Application.routes.draw do

  get "cart/show"
  get "cart/add"
  get "cart/remove"
  post "cart/discount"

  resources :orders

  root :to => 'products#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: :registrations }

  get "user/dashboard"

  resources :user, only: [:show]

  resources :products do
    resources :reviews
  end

  devise_for :users
  ActiveAdmin.routes(self)

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_filter :set_products, only: [:show, :remove, :discount]
  before_filter :set_sum, only: [:show, :remove, :discount]
  before_filter :set_product_id, only: [:add, :remove]
  before_filter :check_coupon_applied, only: [:show, :discount]
  after_filter :discard_flash, only: [:discount]

  def show
    @coupon = DiscountCoupon.new
    set_discount
  end

  def add
    cookies[:products] = encode_cookie(decode_cookie.push(params[:product_id])) unless decode_cookie.include?(params[:product_id])
    @cart_count = @cart_count.to_i + 1
  end

  def remove
    cart = decode_cookie
    if decode_cookie.include?(params[:product_id])
      cookies[:products] = { value: ActiveSupport::JSON.encode(cart -= [params[:product_id]]) }
      @cart_count = @cart_count.to_i - 1
      set_products
      set_sum
      set_discount
    end
  end

  def discount
    if @coupon_applied
      flash[:alert] = "You have already applied a coupon"
    else
      @is_valid_coupon = check_coupon_number
      if @is_valid_coupon
        set_sum
        set_discount
        flash[:notice] = "Congratulations!! you have received a special discount"
      else
        flash[:alert] = "Your coupon number is either invalid or has been consumed"
      end
    end
  end

  private
    def set_products
      return @products = Product.find(decode_cookie) if cookies[:products]
      flash[:alert] = "You don't have any order yet."
    end

    def set_sum
      if @products
        @sum = @products.sum(&:price)
      end
    end

    def set_product_id
      @id = params[:product_id]
    end

    def check_coupon_number
      unless DiscountCoupon.active_coupon(params[:discount_coupon][:coupon_number]).first
        return false
      end
      session[:coupon_number] = params[:discount_coupon][:coupon_number]
      return true
    end

    def check_coupon_applied
      @coupon_applied = true if session[:coupon_number].present?
    end

    def discard_flash
      flash.discard
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add.js.erb
$('#add-<%= @id %>').hide();
$('#cart-count').text('<%= @cart_count %>')

app/views/cart/discount.js.erb
<% if @is_valid_coupon %>
  $('#coupon-field').removeClass('form-group has-error').addClass('form-group has-success');
  $('#sum').text("").append("<del><%= append_currency(@sum) %></del>");
  $('#discounted-price-row').show();
  $('#discounted-sum').text('<%= append_currency(@discounted_sum) %>');
  $('#discount-coupon-form').hide();
  $('#alert-msg').hide();
  $('#notice-msg').show();
  $("#notice-msg").html("<div class='alert alert-info' role='alert'><%= notice %></div>");
<% else %>
  $('#coupon-field').removeClass('form-group has-success').addClass('form-group has-error');
  $("#notice-msg").hide();
  $("#alert-msg").show();
  $('#alert-msg').html("<div class='alert alert-warning' role='alert'><%= alert %></div>");
<% end %>

app/views/cart/remove.js.erb
$('#remove-row-<%= @id %>').hide();
$('#cart-count').text('<%= @cart_count %>');
<% if @discounted_sum.present? %>
  $('#sum').text("").append("<del><%= append_currency(@sum) %></del>");
  $('#discounted-price-row').show();
  $('#discounted-sum').text('<%= append_currency(@discounted_sum) %>');
<% else %>
  $('#sum').text("").append('<strong><%= append_currency(@sum) %></strong>');
  $('#discounted-price-row').hide();
<% end %>

app/views/cart/show.html.erb
<div class="row">
  <div class="col-md-4">
    <h1>Your Order</h1>
  </div>
  <div class="col-md-4 pull-right">
    <%= link_to 'Back to Store', root_path, class: 'btn btn-default btn-sm pull-right store-button' %>
  </div>
</div>

<% if @products.present? %>
  <table class="table" >
    <caption>Your Order</caption>
    <tr>
      <th>Item</th>
      <th>Description</th>
      <th>Price</th>
      <th></th>
    </tr>

    <% @products.each do |product| %>
      <tr id="remove-row-<%= product.id %>">
        <td><%= link_to product.title, product_path(product) %></td>
        <td><%= truncate_string(product.body, 100) %></td>
        <td><%= append_currency(product.price) %></td>
        <td><%= link_to 'Remove', cart_remove_path, id: "remove-#{product.id}", data: { remote: true, params: { product_id: product.id }.to_param }, class: 'btn btn-warning btn-xs' %></td>
      </tr>
    <% end %>
    <tr>
      <td><strong>Grand Total</strong></td>
      <td></td>
      <td>
        <div id="sum">
          <strong>
            <% if @discounted_sum.present? %>
              <del><%= append_currency(@sum) %></del>
            <% else %>
              <%= append_currency(@sum) %>
            <% end %>
          </strong>
        </div>
      </td>
      <td></td>
    </tr>

    <tr id="discounted-price-row" class="<%= @discounted_sum.present? ? 'discount-row' : 'discount-row row-hidden' %>">
      <td><strong>Discounted Price</strong></td>
      <td></td>
      <td><strong><div id="discounted-sum"><%= append_currency(@discounted_sum) %></div></strong></td>
      <td></td>
    </tr>

  </table>

<% unless @coupon_applied %>
  <div class="login-form" id="discount-coupon-form">
    <%= form_for @coupon, url: cart_discount_path , remote: true, html: { id: 'coupon-form' } do |f| %>
      <div class="form-group">
        <%= f.label :coupon_number %>
        <div id="coupon-field"><%= f.text_field :coupon_number, class:"form-control", placeholder: "Enter your special discount coupon number" %></div>
      </div>

      <div class="actions">
        <%= f.submit "Apply Coupon", class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
<% end %>

  <div class="row">
    <div class="col-md-6 pull-right">
      <%= link_to 'Proceed to Checkout', new_order_path, class: 'btn btn-success pull-right' %>
    </div>
  </div>

<% else %>
  <b>You have 0 items in your cart :(</b>
  <div><%= link_to 'Buy Some Products', root_path, class: 'btn btn-success' %></div>
<% end %>