config/routes.rb
Demo::Application.routes.draw do

  get "cart/show"
  get "cart/add"
  get "cart/remove"
  post "cart/discount"

  resources :orders

  root :to => 'products#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: :registrations }

  get "user/dashboard"

  resources :user, only: [:show]

  resources :products do
    resources :reviews
  end

  devise_for :users
  ActiveAdmin.routes(self)

end

app/models/product.rb
class Product < ActiveRecord::Base

  PAGE_SIZE = 12
  paginates_per 5
  REVIEWS_PER_PAGE = 3

  attr_accessible :body, :price, :title, :attachments_attributes, :user_id, :delta

  has_many :attachments, as: :attachable, dependent: :destroy
  has_many  :reviews, dependent: :destroy
  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  belongs_to :user

  validates :body, :price, :title, presence: true
  validates_numericality_of :price, greater_than_equal_to: 0

  accepts_nested_attributes_for :attachments, allow_destroy: true

  scope :ordered, -> { order("created_at desc") }

  define_index do
    indexes body
    indexes title
    set_property delta: true
  end

  def self.perform_search(options)
    options = {} if options.blank?
    search_params  = default_search_options(options)
    self.ordered.search options[:search], search_params
  end

  def self.default_search_options(options)
    {
      page: options[:page],
      per_page: PAGE_SIZE,
    }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :authenticate_user!, except: [:show, :index]
  before_filter :set_product, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @products = Product.ordered.page(params[:page]).per(Product::PAGE_SIZE)
    respond_with(@products)
  end

  def show
    @reviews = @product.reviews.limit(Product::REVIEWS_PER_PAGE)
    @review = Review.new
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = current_user.products.new(params[:product])
    @product.save
    respond_with(@product)
  end

  def update
    return redirect_to product_path, notice: "You can only modify your own Product." unless owner?(@product.user_id)
    @product.update_attributes(params[:product])
    respond_with(@product)
  end

  def destroy
    return redirect_to root_url, notice: "You can only delete your own Product." unless owner?(@product.user_id)
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.includes(:user).find(params[:id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class= "login-form">
  <%= nested_form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class:"form-control", placeholder: "Samsung galaxy note 2" %>
    </div>

    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: "3", class:"form-control", placeholder: "Samsung Galaxy Note II smartphone with 5.50-inch 720x1280 display powered by 1.6GHz processor alongside 2GB RAM and 8-megapixel rear camera."%>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class:"form-control", placeholder: "305.5" %>
    </div>

    <div class="form-group">
      <%= f.fields_for :attachments do |photo_form| %>
        <%= photo_form.file_field :photo if photo_form.object.photo.blank? %>
        <%= image_tag fetch_image(photo_form.object) if photo_form.object.photo.url(:small) %>
        <%= photo_form.link_to_remove "Remove this attachment" %>
      <% end %>
      <p>
        <%= f.link_to_add "Add an attachment", :attachments %>
      </p>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-success"%>
    </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-md-4">
  <%= link_to product do %>
    <%= image_tag fetch_image(product.attachments.first) %>
  <% end %>
</div>
<div class="col-md-8">
  <h5><%= product.title.titleize %></h5>
  <h4><%= append_currency(product.price) %></h4>
  <div class="product-links">
    <%= link_to 'Detail', product, class:"btn btn-success btn-sm" %>
    <%= link_to edit_product_path(product) do %>
      <%= image_tag "edit.jpg", alt: "Edit" %>
    <% end %>
    <%= link_to product, method: :delete, data: { confirm: 'Are you sure to delete this product?' } do %>
      <%= image_tag "cross.png", alt: "Delete" %>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>
<%= image_tag fetch_image(@product.attachments.first) %>

<%= render 'form' %>

<%= link_to 'Back', user_dashboard_path %>

app/views/products/index.html.erb
<% if @products.present? %>
  <h1>Browse Products</h1>
  <%= paginate @products %>

  <div class="row">

    <% @products.each do |product| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <div class ="image-container">
            <%= link_to product do %>
              <%= image_tag fetch_image(product.attachments.first) %>
            <% end %>
          </div>
          <div class="caption">
            <div class="row">
              <div class="col-md-9">
                <h2><%= product.title %></h2>
              </div>
              <div class="col-md-3 product-price">
                <h3><%= append_currency(product.price) %></h3>
              </div>
            </div>
            <h4><%= truncate_string(product.body, 30) %></h4>
            <div>
              <%= link_to 'Details', product, class: "btn btn-primary" %>
              <%= link_to 'Add to cart', cart_add_path, id: "add-#{product.id}", data: { remote: true, target: '#message', toggle: 'modal', params: { product_id: product.id }.to_param }, class: 'btn btn-success' unless in_cart?(product) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>

  </div>

  <%= paginate @products %>
<% else %>
  <h2>Sorry No result found :( </h2>
  <%= link_to 'Browse Products', products_path, class: 'btn btn-success' %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1><%= @product.title %></h1>
  </div>
  <div class="col-md-2 top">
    <%= link_to 'Add to cart', cart_add_path, id: "add-#{@product.id}", data: { remote: true, params: { product_id: @product.id }.to_param }, class: 'btn btn-warning btn-sm' unless in_cart?(@product) %>
  </div>
</div>

<div class="row">
  <% if @product.attachments.present? %>
    <% @product.attachments.each do |attachment| %>
      <div class="col-md-4 thumbnail">
        <%= image_tag fetch_image(attachment) %>
      </div>
    <% end %>
  <% else %>
    <%= image_tag fetch_image(@product.attachments.first) %>
  <% end %>
</div>

<div>
  <h3>Price:<%= append_currency(@product.price) %></h3>
</div>


<div>
  <h3>Description:</h3>
  <%= @product.body %>
</div>

<b>More products from this seller</b>
<%= link_to display_name(@product.user), user_path(@product.user) %>

<h1>Reviews</h1>
<ul id ="show-reviews">
  <% @reviews.each do |review| %>
    <strong><%= link_to display_name(review.user), user_path(review.user) %> says</strong>
    <%= render 'reviews/full_review', review: review %>
    <% if owner?(@product.user_id) %>
      <div>
        <%= link_to product_review_path(@product, review), method: :delete, data: { confirm: 'Are you sure to delete this review?' } do %>
          <%= image_tag "cross.png", alt: "Delete" %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</ul>

<%= link_to 'See All Reviews', product_reviews_path(@product) %>

<% if owner?(@product.user_id) %>
  <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-warning" %>
<% else %>
  <%= render 'reviews/ajax_form' if current_user.present? %>
<% end %>
<%= link_to 'Back', products_path, class: "btn btn-default" %>