config/routes.rb
Demo::Application.routes.draw do

  get "cart/show"
  get "cart/add"
  get "cart/remove"
  post "cart/discount"

  resources :orders

  root :to => 'products#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: :registrations }

  get "user/dashboard"

  resources :user, only: [:show]

  resources :products do
    resources :reviews
  end

  devise_for :users
  ActiveAdmin.routes(self)

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :set_product
  before_filter :set_review, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]
  before_filter :authenticate_review_owner, only: [:edit, :destroy]
  respond_to :html, :js

  def index
    @reviews = @product.reviews
    respond_with(@reviews)
  end

  def show
  end

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    unless owner?(@product.user_id)
      @review = @product.reviews.new(params[:review])
      @review.user_id = current_user.id
      @review.save
      respond_to do |format|
        format.html { redirect_to @product }
        format.js
      end
    end
  end

  def update
    @review.update_attributes(params[:review])
    redirect_to([@product, @review])
  end

  def destroy
    @review.destroy
    redirect_to product_path(@product)
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product_id])
    end

    def authenticate_review_owner
      unless owner?(@review.user_id) || owner?(@product.user_id)
         flash[:notice] = "You can only modify your own reviews."
         redirect_to action: "index"
      end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_ajax_form.html.erb
<%= form_for([@product, @review], remote: true, html: { id: 'review-form' }) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="comment-form">
    <%= f.label :post_your_review %>
    <div><%= f.text_area :comment, rows: "3", class:"form-control" %></div>
  </div>

  <div class"row" >
    <div class="form-group right">
      <%= f.submit "Comment", class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/reviews/_form.html.erb
<div class="comment-form">
  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %>
      <%= f.text_area :comment, rows: "3", class:"form-control" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/reviews/_full_review.html.erb
<li>
  <%= review.comment %>
</li>

app/views/reviews/_review.html.erb
<%= truncate_string(review.comment, 25) %>

app/views/reviews/create.js.erb
<% if @review.comment.length > 1 %>
  $('#show-reviews').append('<strong><%= link_to display_name(@review.user), user_path(@review.user) %> says</strong><li><%= @review.comment.gsub(/[\n\r\t]/, '') %></li>');
<% else %>
  alert("Too short review");
<% end %>
$('#review-form')[0].reset();

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= image_tag fetch_image(@product.attachments.first) %>

<%= render 'form' %>

<%= link_to 'Back', user_dashboard_path %>

app/views/reviews/index.html.erb
<h1><%= @product.title %></h1>

<table class="table">
  <tr>
    <th>Reviews</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @reviews.each do |review| %>
    <tr>
      <td><%= link_to review.comment, product_path(@product) %></td>
      <td>
        <% if owner?(review.user_id) %>
          <%= link_to 'Edit', edit_product_review_path(@product, review), class:"btn btn-warning btn-xs" %>
        <% end %>
      </td>
      <td>
        <% if owner?(review.user_id) || owner?(@product.user_id) %>
          <%= link_to 'Destroy', product_review_path(@product, review), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-xs" %>
        <% end %>
      </td>
    </tr>
  <% end %>

</table>

<%= link_to 'New Review', new_product_review_path(@product) %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', product_reviews_path(@product) %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>


<%= link_to 'Edit', edit_product_review_path(@product) %> |
<%= link_to 'Back', product_reviews_path(@product) %>