config/routes.rb
Demo::Application.routes.draw do

  get "cart/show"
  get "cart/add"
  get "cart/remove"
  post "cart/discount"

  resources :orders

  root :to => 'products#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { registrations: :registrations }

  get "user/dashboard"

  resources :user, only: [:show]

  resources :products do
    resources :reviews
  end

  devise_for :users
  ActiveAdmin.routes(self)

end

app/views/layouts/_footer.html.erb
<footer role="navigation">
  <div class="container footer-div">
    <nav>
      <ul class="nav navbar-nav navbar-right nav-pills">
        <li><%= link_to '', cart_show_path, class:"glyphicon glyphicon-shopping-cart" %></li>
        <li><%= link_to 'Contact Us', "/contact" %></li>
        <li><%= link_to 'Facebook', "https://www.facebook.com/shopify" %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="bs-example">
    <nav role="navigation" class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Shopify', root_path, class: "navbar-brand" %>
        </div>
        <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right nav-pills">
            <li class="navbar-form" role="search">
              <%= form_tag products_path, method: 'get' do %>
                <p>
                  <%= text_field_tag :search, nil, placeholder: 'Enter search term...', class: "form-control"%>
                </p>
              <% end %>
            </li>
            <li>
              <div class="cart-icon">
                <%= link_to cart_show_path, class:"glyphicon glyphicon-shopping-cart" do %>
                  <span class="badge" id="cart-count"><%= @cart_count %></span>
                <% end %>
              </div>
            </li>
            <% if user_signed_in? %>
              <li><%= link_to 'New Product', new_product_path %></li>
              <li><%= link_to "Dashboard", user_dashboard_path %></li>
              <li><%= link_to "Update Profile", edit_user_registration_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Signup", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Demo</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "https://js.stripe.com/v1/", "application" %>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: "stripe-key", content: STRIPE_PUBLIC_KEY %>
  </head>
  <div class="wrap-container">
    <body class="container demo-container">

      <%= render 'layouts/header' %>

    <div id="notice-msg">
      <% if notice %>
        <div class="alert alert-info" role="alert"><%= notice %></div>
      <% end %>
    </div>

    <div id="alert-msg">
      <% if alert %>
        <div class="alert alert-warning" role="alert"><%= alert %></div>
      <% end %>
    </div>

      <%= yield %>

    </body>
  </div>

    <%= render 'layouts/footer' %>

</html>